[platformio]
core_dir = ../../../.platformio-home
default_envs = esp32dev

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
build_flags =
  -pipe
lib_deps =
  monophonic-instrument=file://../monophonic-instrument
  m5stack/M5Unified@0.2.17
