[platformio]
core_dir = ../../../.platformio-home

[env:esp32dev]
platform = platformio/espressif32@7.0.1
board = esp32dev
framework = arduino
lib_deps =
  monophonic-instrument=file://../../../packages/monophonic-instrument
  m5-tone-output=file://../../../packages/m5-tone-output
