[platformio]
core_dir = ../../../.platformio-home
default_envs = esp32dev

[env:esp32dev]
platform = platformio/espressif32@7.0.1
board = esp32dev
framework = arduino
build_flags =
  -pipe
lib_deps =
  monophonic-instrument=file://../monophonic-instrument
  m5stack/M5Unified@0.2.17
